sudo: true
dist: trusty

language: c

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
      # GHC
      - libgmp-dev


cache:
  directories:
    - $HOME/.stack
    - .stack-work

matrix:
  include:
    - env: ARGS=""
    - env: ARGS="--resolver nightly"

  allow_failures:
    - env: ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

- travis_retry wget http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo chmod u+x chromedriver
- sudo mv chromedriver /usr/bin/

before_script:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- google-chrome --version
- travis_retry wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
- java -jar selenium-server-standalone-2.53.1.jar 2> /dev/null &
- sleep 5

script:
 - stack $ARGS --no-terminal --install-ghc build --test
